name: rlbook
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchaudio==2.3.1
  - pytorch-cuda=12.1
  - gymnasium[atari]==0.29.1
  - gymnasium[classic-control]==0.29.1
  - gymnasium[accept-rom-license]==0.29.1
  - moviepy==1.0.3
  - numpy==1.26.3
  - tensorboard==2.15.1
  - mypy==1.8.0
  - stable-baselines3==2.2.1
  - pytest
  - pip
  - pip:
      - torchrl==0.4.0
      - ray[tune]
      - pytorch-ignite==0.4.13
      - ptan==0.8
      - opencv-python==4.9.0.80
      - gymnasium[accept-rom-license]
      - autorom[accept-rom-license]
